### ISSUE TITLE
Feature request: The option to include highlights that cannot be displayed in the parsed results.

### ISSUE THREAD

**Issue by sitogi** [azu/kindle-highlight-to-markdown#3]
## Description

I would like the option to include highlights that cannot be displayed in the analysis results.

## Background

I believe the main use case for this tool is to transcribe Kindle highlights to a personal notes tool or similar so that they can be easily referenced from there.
With the current behavior of skipping highlights that cannot be displayed, I could not track which highlights were skipped, and ended up having to go to the "Notes and Highlights" page.

Even if we don't know the contents of the highlights, we would like to have an option to not skip content that cannot be displayed, because if we know the location, etc., we will be able to follow it from the transcribed memo tool.

**Comment by azu** [comment]
fixed in #4 

I've supported empty highlight and added `defaultHighlightMessage` option to `toMarkdown`

<img width="437" alt="image" src="https://user-images.githubusercontent.com/19714/204550205-4bd30583-86a8-4b5d-8d0f-55f7c2b24ecd.png">

→

<img width="610" alt="image" src="https://user-images.githubusercontent.com/19714/204550243-f7f5a770-739d-478c-bf0f-9374aed13291.png">


```js
const { parsePage, toMarkdown } = await import('https://cdn.skypack.dev/kindle-highlight-to-markdown@1.2.0');
const result = parsePage(window); // JSON Object
const markdown = toMarkdown(result); // Markdown
copy(markdown);
```
